apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tsdnsproxy

resources:
- deployment.yaml

images:
- name: tsdnsproxy
  newName: ghcr.io/rajsinghtech/tsdnsproxy  # Update with your registry
  newTag: latest

secretGenerator:
- name: tsdnsproxy-auth
  namespace: tsdnsproxy
  literals:
  - TS_AUTHKEY=tskey-auth-REPLACE-ME  # Replace with actual key
  options:
    disableNameSuffixHash: true

configMapGenerator:
- name: tsdnsproxy-config
  namespace: tsdnsproxy
  literals:
  - TSDNSPROXY_OVERRIDE_DNS=8.8.8.8:53,8.8.4.4:53
  - TSDNSPROXY_VERBOSE=true