apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tsdnsproxy

resources:
- deployment.yaml

images:
- name: tsdnsproxy
  newName: ghcr.io/rajsinghtech/tsdnsproxy
  newTag: "1.1.3"

secretGenerator:
- name: tsdnsproxy-auth
  namespace: tsdnsproxy
  literals:
  - TS_AUTHKEY_EPHEMERAL=tskey-auth-REPLACE-ME
  options:
    disableNameSuffixHash: true

configMapGenerator:
- name: tsdnsproxy-config
  namespace: tsdnsproxy
  literals:
  - TSDNSPROXY_VERBOSE=true
  options:
    disableNameSuffixHash: true
